# Fly.io Dev Environment Configuration - Asset Service
# App: gaia-asset-dev
# Organization: aeonia-dev

app = 'gaia-asset-dev'
primary_region = 'lax'

[build]
  dockerfile = "Dockerfile.asset"

[env]
  ENVIRONMENT = "dev"
  SERVICE_NAME = "asset"
  LOG_LEVEL = "DEBUG"
  SERVICE_PORT = "8000"
  
  # Database - Fly.io Managed Postgres (dev environment)
  DATABASE_URL = "postgresql://postgres@gaia-db-dev.internal:5432/postgres"
  
  # NATS for service coordination
  NATS_URL = "nats://gaia-nats-dev.fly.dev:4222"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.timeout]
    idle = "30m"

[[vm]]
  memory = '1gb'  # Asset service needs more memory for image processing
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "rolling"

# Health checks for asset service
[[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "https"
  timeout = "2s"