# Fly.io Dev Environment Configuration - Gateway Service
# App: gaia-gateway-dev
# Organization: aeonia-dev

app = 'gaia-gateway-dev'
primary_region = 'lax'

[build]
  dockerfile = "Dockerfile.gateway"

[env]
  ENVIRONMENT = "dev"
  SERVICE_NAME = "gateway"
  LOG_LEVEL = "DEBUG"  # More verbose logging for dev
  
  # Full microservices URLs (dev environment)
  AUTH_SERVICE_URL = "https://gaia-auth-dev.fly.dev"
  ASSET_SERVICE_URL = "https://gaia-asset-dev.fly.dev"
  CHAT_SERVICE_URL = "https://gaia-chat-dev.fly.dev"
  
  # Database - Fly.io Managed Postgres (dev environment)
  DATABASE_URL = "postgresql://postgres@gaia-db-dev.internal:5432/postgres"
  
  # NATS for service coordination
  NATS_URL = "nats://gaia-nats-dev.fly.dev:4222"
  
  # Supabase for JWT auth only - set via secrets
  # fly secrets set SUPABASE_URL=... SUPABASE_ANON_KEY=... SUPABASE_JWT_SECRET=...

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1  # Dev: single instance is fine
  processes = ['app']

[[vm]]
  memory = '1gb'  # Dev: moderate resources
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "rolling"  # Dev: safe deployment strategy

# Health checks for dev
[[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "https"
  timeout = "2s"