# Fly.io Development Environment Configuration
# App: gaia-gateway-dev

app = 'gaia-gateway-dev'
primary_region = 'sjc'

[build]
  dockerfile = "Dockerfile.gateway"

[env]
  ENVIRONMENT = "development"
  SERVICE_NAME = "gateway"
  LOG_LEVEL = "DEBUG"
  
  # Service URLs for dev environment
  AUTH_SERVICE_URL = "https://gaia-auth-dev.fly.dev"
  ASSET_SERVICE_URL = "https://gaia-asset-dev.fly.dev"
  CHAT_SERVICE_URL = "https://gaia-chat-dev.fly.dev"
  
  # Database - must be set via secrets:
  # ./scripts/set-fly-secrets.sh dev
  # Or manually: fly secrets set DATABASE_URL="..." -a gaia-gateway-dev
  
  # NATS
  NATS_URL = "nats://gaia-nats-dev.fly.dev:4222"
  
  # Redis (Upstash Redis on Fly.io)
  REDIS_URL = "redis://fly-gaia-redis-dev.upstash.io:6379"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.timeout]
    idle = "30m"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "immediate"