# Fly.io Dev Environment Configuration - Auth Service
# App: gaia-auth-dev
# Organization: aeonia-dev

app = 'gaia-auth-dev'
primary_region = 'sjc'

[build]
  dockerfile = "Dockerfile.auth"

[env]
  ENVIRONMENT = "dev"
  SERVICE_NAME = "auth"
  LOG_LEVEL = "DEBUG"
  SERVICE_PORT = "8000"
  
  # Database - Fly.io Managed Postgres (dev environment)
  DATABASE_URL = "postgresql://postgres@gaia-db-dev.internal:5432/postgres"
  
  # NATS for service coordination
  NATS_URL = "nats://gaia-nats-dev.fly.dev:4222"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.timeout]
    idle = "30m"
  
  [[http_service.checks]]
    method = "GET"
    path = "/health"
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"

[[vm]]
  memory = '512MB'  # Auth service needs less memory
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "rolling"
