# Fly.io Production Environment Configuration
# App: gaia-gateway-prod

app = 'gaia-gateway-prod'
primary_region = 'sjc'

[build]
  dockerfile = "Dockerfile.gateway"

[env]
  ENVIRONMENT = "production"
  SERVICE_NAME = "gateway"
  LOG_LEVEL = "WARNING"
  
  # Service URLs for production environment
  AUTH_SERVICE_URL = "https://gaia-auth-prod.fly.dev"
  ASSET_SERVICE_URL = "https://gaia-asset-prod.fly.dev"
  CHAT_SERVICE_URL = "https://gaia-chat-prod.fly.dev"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

# Production scaling configuration
[[vm]]
  memory = '2gb'
  cpu_kind = 'performance'
  cpus = 2

[deploy]
  strategy = "rolling"
  max_unavailable = 1

# Comprehensive health checks for production
[[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "https"
  timeout = "2s"
  
[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"