# Fly.io Production Environment Configuration
# App: gaia-gateway-production
# Organization: aeonia-dev

app = 'gaia-gateway-production'
primary_region = 'lax'

[build]
  dockerfile = "Dockerfile.gateway"

[env]
  ENVIRONMENT = "production"
  SERVICE_NAME = "gateway"
  LOG_LEVEL = "INFO"
  
  # For initial deployment, use embedded services (all in gateway)
  # Change these URLs when deploying full microservices
  AUTH_SERVICE_URL = "http://localhost:8000"
  ASSET_SERVICE_URL = "http://localhost:8000"
  CHAT_SERVICE_URL = "http://localhost:8000"
  KB_SERVICE_URL = "https://gaia-kb-production.fly.dev"
  
  # Database - Fly.io Managed Postgres (co-located in LAX)
  # DATABASE_URL must be set via secrets:
  # ./scripts/set-fly-secrets.sh production
  # Or manually: fly secrets set DATABASE_URL="..." -a gaia-gateway-production
  # TODO: Create separate production database (currently using staging DB)
  
  # Supabase for JWT auth only - set via secrets
  # fly secrets set SUPABASE_URL=... SUPABASE_ANON_KEY=... SUPABASE_JWT_SECRET=...
  
  # Disable NATS for initial cloud deployment
  NATS_URL = "disabled"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 2  # Production: higher availability
  processes = ['app']

[[vm]]
  memory = '2gb'  # Production: more memory
  cpu_kind = 'shared'
  cpus = 2        # Production: more CPU

[deploy]
  strategy = "rolling"  # Production: safer deployment strategy

# Health checks for production
[[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "https"
  timeout = "2s"

