app = "gaia-web-dev"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile.web"

[env]
  SERVICE_NAME = "web"
  ENVIRONMENT = "dev"
  LOG_LEVEL = "DEBUG"
  PRIMARY_REGION = "lax"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.timeout]
    idle = "30m"

  [http_service.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 450

  [[http_service.checks]]
    method = "GET"
    path = "/health"
    interval = "30s"
    timeout = "10s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256