# Fly.io Staging Environment Configuration
# App: gaia-gateway-staging

app = 'gaia-gateway-staging'
primary_region = 'lax'

[build]
  dockerfile = "Dockerfile.gateway"

[env]
  ENVIRONMENT = "staging"
  SERVICE_NAME = "gateway"
  LOG_LEVEL = "INFO"
  
  # For now, use embedded services (all in gateway)
  AUTH_SERVICE_URL = "http://localhost:8000"
  ASSET_SERVICE_URL = "http://localhost:8000"
  CHAT_SERVICE_URL = "http://localhost:8000"
  KB_SERVICE_URL = "https://gaia-kb-staging.fly.dev"
  
  # Database - Fly.io Managed Postgres (co-located in LAX)
  # DATABASE_URL must be set via secrets:
  # ./scripts/set-fly-secrets.sh staging
  # Or manually: fly secrets set DATABASE_URL="..." -a gaia-gateway-staging
  
  # Supabase for JWT auth only
  # SUPABASE_URL = "https://[project].supabase.co"
  # SUPABASE_ANON_KEY = "[anon_key]" 
  # SUPABASE_JWT_SECRET = "[jwt_secret]"
  
  # Disable NATS for initial cloud deployment
  NATS_URL = "disabled"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "canary"

# Health checks for staging
[[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "https"
  timeout = "2s"