# Fly.io Dev Environment Configuration - NATS Service
# App: gaia-nats-dev
# Organization: aeonia-dev

app = 'gaia-nats-dev'
primary_region = 'lax'

[build]
  image = "nats:2.10-alpine"

[env]
  ENVIRONMENT = "dev"

[http_service]
  internal_port = 4222
  force_https = false  # NATS uses raw TCP
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  processes = ["app"]
  protocol = "tcp"
  internal_port = 4222

  [[services.ports]]
    port = 4222
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[vm]]
  memory = '256Mi'  # NATS is lightweight
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "rolling"